### ISSUE TITLE
Error: k <= n is not TRUE

### ISSUE THREAD

**Issue by kinshh92** [USGS-R/EflowStats#16] opened 2015-05-13 23:05 UTC
Hi - I am getting an error in the FlowStatsAll function that says: 'Error: k <= n is not TRUE" 

A quick Google search looks like this error typically occurs when NA values are present while calculating a rolling mean. My flow time series does not contain NA values, and I have previously used this function successfully. 

Has anyone else seen a similar error or have any ideas what might be happening?

**Comment by dblodgett-usgs** [comment] 2015-05-19 15:49
I have come across this error before. @jlthomps, can you advise as to why this is happening?

**Comment by dblodgett-usgs** [comment] 2015-06-01 12:32
@kinshh92, have you found a solution to this? I searched back through my notes and found this note. 'It works when I set my time range as  startdate <- "2008-10-01" enddate <- "2013-09-29" but not with enddate<-"2013-10-01"'

Not sure if a minor date change will fix it, I will try and get an R developer with some time to look at this more closely. Can you provide some more guidance on how you reproduce this?

Thanks!

**Comment by kinshh92** [comment] 2015-06-01 13:33
I have not figured it out yet but I haven't given it very much attention yet. 

The error is occurring for the USGS gage 01631000 which is on the SF Shenandoah River at Front Royal. The date range is 1930-09-22 to 2014-11-18, and I have been cutting it off at 2014-09-30. Maybe the start date is throwing it off because it doesn't start at the first day of a water year? I will investigate in the next couple of days and see if the date correction fixes it. 

Thanks for the ideas! 

Kinsey

**Comment by tmills-usgs** [comment] 2016-02-04 19:57
Unable to reproduce the error with the sites and information provided. Closing for now but will reopen if error occurs again. @kinshh92

**Closed** 2016-02-04 20:15 UTC
Labels: bug
